### ISSUE TITLE
Arm64 image uses incorrect version of crictl package

### ISSUE THREAD

**Issue by InariTheFox** [ssup2/kpexec#13]
Good day,

In attempting to use your tools on an Arm64 based AWS cluster (AWS R6G machine), I discovered that your Dockerfile specifies the linux-amd64 crictl package, and not the appropriate Arm64 variant.

I hope you can look in to this.

Thank you!

**Comment by ssup2** [comment]
@InariTheFox Yes. you're right. I'll fix it :)

**Comment by ssup2** [comment]
@InariTheFox Hello. Cloud you test with latest (0.4.1) Version?

**Comment by hjf288** [comment]
@ssup2 This is still an issue - I've created a PR for it:

https://github.com/ssup2/kpexec/pull/18
