### ISSUE TITLE
How do I determine if my cluster supports kpexec's requirements? 'failed to create cnsetner pod: admission webhook "validating-webhook.openpolicyagent.org" denied the request'

### ISSUE THREAD

**Issue by trtg** [ssup2/kpexec#14]
I'm unable to use kpexec on my cluster and wanted to know what features I need to check to know whether things should be compatible. The full error message is:
```
Failed to run kpexec err : failed to create cnsetner pod (cnsenter-1234) : admission webhook "validating-webhook.openpolicyagent.org" denied the request: Sharing the namespace is not allowed: cnsenter-1234. The vol type hostPath is not allowed, pod: cnsenter-1234
```

**Comment by ssup2** [comment]
When run kpexec, cnsenter pod is created. cnsenter pod must be created with "hostPID", "hostPath" and "privilieged" options. Your error message looks like that OPA prevent creating pod with "hostPath".
