### ISSUE TITLE
Promote to official kubectl

### ISSUE THREAD

**Issue by mcandre** [ssup2/kpexec#7]
Thank you for maintaining this very helpful tool! I would love to see this capability promoted into the main kubectl client, so that this feature will be available out of the box for all Kubernetes setups.

**Comment by ssup2** [comment]
@mcandre Thanks :). 

Exec with privilege is very reluctant issue. https://github.com/kubernetes/kubernetes/issues/30656
So now I haven't any plan to promote kpexec. Please tell the people around you to use kpexec a lot.

Thanks :)
