### ISSUE TITLE
Allow more conventional --namespace / -n flag placement

### ISSUE THREAD

**Issue by mcandre** [ssup2/kpexec#8]
Hey, I don't know if this is a problem with kpexec specifically, or more likely the kubectl plugin system. But it's annoying to not be able to use `--namespace` / `-n` before the `pexec` subcommand.

When operating on a lot of different namespaces, it is practical to declare the namespace early rather than late in kubectl commands.

**Comment by ssup2** [comment]
@mcandre I've known this issue. But this is the limitation of kubectl. This is one of the reasons why I developed kpexec as a standalone binary before kubectl plugin.
